### ISSUE TITLE
Get the Travis build to work.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#27]
It always fails while installing `bcrypt`.

**Comment by marshallswain** [comment]
Had to modify the travis.yml
```yml
language: node_js
node_js:
  - '4.2.3'
  - 'iojs'
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-4.9 g++-4.9 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 20
  - gcc --version
```
Last line not needed, but I'm done force pushing this poor branch.  :)
